### ISSUE TITLE
When one operation has many tags, click sidebar always turn to first one. 

### ISSUE THREAD

**Issue by Drunkman** [Redocly/redoc#1119]
When one operation has many tags, but only has one operationId. The sidebar will generate many item in different tags, but their operationIds are same, so click them will turn to same anchor. It is confusing.

For example, the `Tag1` and `Tag2` both have `operation_1`, but when click `operation_1` in `Tag2`, it will turn to `operation_1` in `Tag1`.
``` json
"post": {
        "tags": [
          "Tag1",
          "Tag2"
        ],
        "operationId": "operation_1",
        ...
}
```
![image](https://user-images.githubusercontent.com/10599065/69940745-f234c180-151d-11ea-8190-3b7c71b520dd.png)

**Comment by JeremiasIsnardy** [comment]
We're also starting to use multiple tags and x-tagGroups.
It's really confusing for the api user when she/he is interested in methods of this section, defined by such a group and gets redirected to another section. 
I understand the issue, there is only one anchor (of course) in the content page. Jumping there is  necessary, but could you somehow suppress this sidebar "jump", so that the selected menu stays at that position?

**Comment by RomanHotsiy** [comment]
Should be fixed when this lands https://github.com/Redocly/redoc/pull/1245

**Comment by RomanHotsiy** [comment]
Actually dup of https://github.com/Redocly/redoc/issues/777
