### ISSUE TITLE
Side-menu : operation-type label width too short when display "PATCH" in Chrome.

### ISSUE THREAD

**Issue by mzone** [Redocly/redoc#1180]
Side-menu : operation-type label width too short when display "PATCH" in Chrome.

Probably the cause by font-size. Chorme can't diplay font size less than 10px.

I want to change here.
```
# src/components/SideMenu/styled.elements.ts
# className: `operation-type ${props.type}`
-  width: 32px;
+  width: 6.5em;
```

| as-is | to-be |
|---|---|
| <img width="280" alt="74829928-6c265b00-5355-11ea-9945-13dd49b9a83a" src="https://user-images.githubusercontent.com/1255599/75016818-2b525180-54cf-11ea-9382-499e92830387.png"> | <img width="281" alt="74829974-806a5800-5355-11ea-93e2-4f166e25748c" src="https://user-images.githubusercontent.com/1255599/75016827-2ee5d880-54cf-11ea-8f72-98b46a90868c.png"> |

thanks..

**Comment by RomanHotsiy** [comment]
It looks fine for me 
![image](https://user-images.githubusercontent.com/3975738/81507979-b93d1c00-9309-11ea-9acb-72949c0918fc.png)

Can you provide more details? What OS and monitor do you use?

**Comment by mariusa** [comment]
![Screenshot from 2020-05-27 12-31-02](https://user-images.githubusercontent.com/1283842/83002742-12999080-a016-11ea-8931-72a2ed01edfd.png)

Linux, Chrome 82 with larger font size & minimum:
![Screenshot from 2020-05-27 12-33-09](https://user-images.githubusercontent.com/1283842/83002914-4674b600-a016-11ea-89ba-82bc34b18bf3.png)

**Comment by mzone** [comment]
> It looks fine for me
> ![image](https://user-images.githubusercontent.com/3975738/81507979-b93d1c00-9309-11ea-9acb-72949c0918fc.png)
> 
> Can you provide more details? What OS and monitor do you use?

Sorry I haven't been able to reply.

OS: macOS Catalina 10.15.5
Browser: google Chrome 81.0.4044.138
MacBook Pro (15-inch, 2019)

still have that problem X<
Maybe, a problem with the font... I'm using japanese font 'font-family:HiraginoSans-W3' (typical japanese  font in mac)

thanks.

**Comment by wopian** [comment]
Also facing this problem with the default settings (besides colours) when the header weight is modified.

```
--options.theme.typography.headings.fontWeight=700
```

`bold/700` font weight:

![image](https://user-images.githubusercontent.com/3440094/90455740-c2027280-e0ee-11ea-915e-ca2a5686f1c9.png)

`normal/400` font weight:

![image](https://user-images.githubusercontent.com/3440094/90455813-f5450180-e0ee-11ea-9306-3c6276dc376b.png)

**Comment by RomanHotsiy** [comment]
Oh, must be some OS-font related. I will check this up.

**Comment by RomanHotsiy** [comment]
I just opened redoc demo on windows 10 using Chrome and the patch fits into the box. I can't reproduce the issues you have.

**Comment by wopian** [comment]
Using `Roboto,sans-serif`\* (the root font-family of Redoc) instead of `Verdana` makes it just about contained in the label.

![image](https://user-images.githubusercontent.com/3440094/90695961-5b5a9180-e273-11ea-8db2-89667dd9e663.png)

\* My system-default `sans-serif` computes to `Noto Sans` which also fits, but it may be different for other systems.

---

For the Linux comment above, it seems some browsers/OS' fallback to a `serif` font for `Verdana`. Appending `sans-serif` to the label's `font-family` should avoid that.

**Comment by wopian** [comment]
Update: the root cause of this issue is to do with `font-size` accessibility with the `Minimum font size` property in browsers.

Redoc sets the label `font-size` to `7px` (which is unreadably small in most fonts other than `Verdana`).

On Chrome, my `Minimum font size` is set to `10px`. In FireFox and (Chromium) Edge, the `Minimum font size` appears to be set to `None` by default and does render the labels as expected. The default may be `None` for Chrome too and I may have just changed it at some point in the past.

With `Minimum font size` set above `7px`, the computed `font-size` of the label is increased from `7px` to whatever the minimum font size is. In the case for me it computes to `10px`, which is too big for the fixed-width label size.

On Firefox and Edge:
![image](https://user-images.githubusercontent.com/3440094/90697319-0cfac200-e276-11ea-9c9b-1a2d0a876ee7.png)

## Working Solution (`9ex`)

Setting units in `px` and `(r)em` use the CSS-defined `font-size` units (in this case `7px`) and not the computed `font-size`, which means the label size does not scale with the increased minimum font sizes.

Setting the label width to `9ex` mimics the current intended behaviour at 7px:
![image](https://user-images.githubusercontent.com/3440094/90698025-aa0a2a80-e277-11ea-80bc-563826622e97.png)

When the minimum font size is increased, the label width scales accordingly to the computed font size. For example, here's `9ex` with a `10px` computed font size:
![image](https://user-images.githubusercontent.com/3440094/90698043-b2626580-e277-11ea-8013-fc2a895ba8d0.png)

And here's `10px` minimum font size on a 4K display with `9ex`:
![image](https://user-images.githubusercontent.com/3440094/90698213-1be27400-e278-11ea-9b4f-1c77cafa080e.png)


---

If you were to instead use `6.5em`, with a computed font size of `7px`, you would have the second image's width with the first image's font size which is not ideal.
![image](https://user-images.githubusercontent.com/3440094/90698095-d2922480-e277-11ea-833a-105505a306e7.png)
