### ISSUE TITLE
Fetch from the same site fails on CORS

### ISSUE THREAD

**Issue by crazyshot** [Redocly/redoc#1232]
I'm loading the resource from the same domain.
`<redoc spec-url='./api.yml'></redoc>`
I expect it to be loaded without any CORS requirement, however in the request headers I see:
>origin: null
>sec-fetch-dest: empty
>sec-fetch-mode: cors
>sec-fetch-site: cross-site

And it fails with:
> Access to fetch at 'https://[my-host]/LazyAPI_20doc/api.yml' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

What am I missing?
Might be the same as #1181 but that one was closed without any comment, so...

**Comment by RomanHotsiy** [comment]
Where do you load redoc js from? I suspect you load it from CDN.

**Comment by RomanHotsiy** [comment]
Closing as stale. Feel free to reopen/continue it here.

**Comment by rameshpongalur** [comment]
I am getting same error. loading using CDN. Both JSON URL and request URL both placed in locally. Can I know how to solve his issue?

**Comment by elefantelimpio** [comment]
Hi, I'm having the same problem as @rameshpongalur experienced. I have my react app bundled on an S3 bucket together with my swagger files and It throws unexpected error:

Error: Error downloading https://xxxxxx.com/docs/myswagger.json 
NetworkError when attempting to fetch resource.

I've protected my url because is a private environment
