### ISSUE TITLE
Webhooks support OAS 3.1

### ISSUE THREAD

**Issue by Herrick19** [Redocly/redoc#1327]
Hi,

There was callbacks, but now OAS 3.1 supports Webhooks as well.

It's pretty much the same structure as a Callback but out of scope of a path. It would be nice if you could support it.

Ref: https://github.com/OAI/OpenAPI-Specification/issues/1968 (Feature request)
Ref: https://github.com/OAI/OpenAPI-Specification/pull/2103 (Pull Request)
Ref: https://github.com/OAI/OpenAPI-Specification/pull/2103/files/3fb1bffff5ef599418420e7d27593418deeaa2a3#diff-d2aac6cc1f8743d6fda6b4932242c6eb (Example file)

Since these are not associated to a path, they could perhaps have their own section in the left menu.

Thanks in advance

**Comment by adamaltman** [comment]
See here: https://github.com/Redocly/redoc/pull/1304

We plan to merge it next week (we hope).

**Comment by Herrick19** [comment]
I've check #1304 

You have implemented it as "x-webhooks", but since it will be supported as "webhooks" in 3.1, shouldn't you remove the "x-" ?

Or for now you will have the "x-" and remove it eventually ?

Best Regards

**Comment by adamaltman** [comment]
It is implemented as `x-webhooks` for forward compatibility. This means someone who is using OAS 3.0 can use this new feature without adopting 3.1 (which currently has a release candidate, but is not in general release yet). There will need to be a set of tasks to add support for 3.1 (yes, the webhooks support will be quite easy because it is already done with x-webhooks, but there are quite a few other differences between 3.1 and 3.0).
