### ISSUE TITLE
redoc-cli fails to install due to missing dependency (mobx-react-lite)

### ISSUE THREAD

**Issue by jbaileyashe** [Redocly/redoc#1398]
I've been using redoc-cli successfully for months. Now, it won't install. It fails with the error message "mobx-react-lite@3 requires mobx at least version 6 to be available".

To reproduce, use docker:

```bash
$ docker run --rm node:alpine npx redoc-cli@ --help
mobx-react-lite@3 requires mobx at least version 6 to be available
```

**Comment by andrewjensen** [comment]
Seeing this as well.

**Comment by leftwichj** [comment]
I've noticed a new version of both mobx and mobx-react-lite was published in the last few hours, and have had this issue since.

**Comment by andrewjensen** [comment]
I dug into the issue some more.

[mobx-react](https://github.com/mobxjs/mobx-react) 7.0.0 and [mobx-react-lite](https://github.com/mobxjs/mobx-react-lite) 3.0.0 were just published earlier today.

The dependency tree looks like this: (From an `npm ls` command today)

```
└─┬ redoc-cli@0.9.12
  └─┬ redoc@2.0.0-rc.40
    └─┬ mobx-react@6.3.0
      └── mobx-react-lite@3.0.0
```

Notice that we're on an older version of mobx-react, but a new, incompatible version of mobx-react-lite beneath it, which expects mobx version 6. redoc-cli requires mobx version 4, so there is a conflict which causes npx to fail.

So we are getting a version of mobx-react-lite that is too new for everything above it. This is because of a lax versioning requirement by mobx-react:

https://github.com/mobxjs/mobx-react/blob/6.3.0/package.json#L93

```
  "dependencies": {
    "mobx-react-lite": ">=2.2.0"
  }
```

So the root cause of this is arguably that the older versions of mobx-react are too lax in their requirements and are causing downstream projects like redoc to break. I'll go open an issue with them and see if they can publish a 6.x patch that tightens up the requirement.

In the meantime, if they're not able to do that, redoc can probably pin a version of the transitive mobx-react-lite dependency to get things working again.

The longer term fix is to get redoc upgraded to use newer versions of mobx and its bindings.

**Comment by leftwichj** [comment]
As a temp workaround I was able to change my docker file like so with success

`RUN npm install -g react react-dom mobx@5.15.4 mobx-react-lite@2.2.2 styled-components core-js redoc-cli@0.9.12`

**Comment by jbaileyashe** [comment]
Issue fixed by mobx.

**Comment by rlauriston** [comment]
I'm still getting this. Tried the workaround @leftwichj posted and that didn't help either.
