### ISSUE TITLE
Generated openapi.json is missing 'type' for Enum query params

### ISSUE THREAD

**Issue by mikemaccana** [Redocly/redoc#1514]
I'm new to Redoc, and not entirely sure if this is a bug or not - thanks for your patience. The `openapi.json` generated by Redoc is missing the `type` key for Enum values, which breaks parsing by other tools, eg [openapi-snippet](https://www.npmjs.com/package/openapi-snippet).

The following is copied from https://stackoverflow.com/questions/66011610/fastapi-redoc-created-openapi-json-is-missing-type-key-for-enum-params - you're welcome to answer there if I'm doing something wrong!

I have a REST API build using FastAPI, with various query string params that are all working fine, generating working `openapi.json` output:

```python
flagged: bool = False,
```

Generates:

```
{
  "required": false,
  "schema": {
    "title": "Flagged",
    "type": "boolean"
  },
  "name": "flagged",
  "in": "query"
}
```

However I have some params that use Enum values. The resulting openAPI definition is missing a `type` specifier - 

```python
sortby: TaskSortby = TaskSortby.confusion,
```

Generates:

```
 {
  "required": false,
  "schema": {
    "allOf": [
      {
        "$ref": "#/components/schemas/TaskSortby"
      }
    ],
    "default": "confusion"
  },
  "name": "sortby",
  "in": "query"
}
```

As you can see `schema.type` is missing, which causes other tools that read `openapi.json` files to break.

How can I generate an `openapi.json` with `type` key for Enum params?

**Comment by lornajane** [comment]
First of all, I'm very sorry for the slow response, I realise this issue has been open a while. I'll be honest, Redoc is a documentation renderer, it doesn't generate OpenAPI, so I also don't understand your question. I'm therefore closing the issue since I think it's unlikely we can do anything helpful at this point. BUT if you're still running into problems, or see this again in the future, do please go ahead and open a new issue so we can look afresh at what might be happening.
