### ISSUE TITLE
Properties's example isn't being rendered in the docs

### ISSUE THREAD

**Issue by nikolajokicmvp** [Redocly/redoc#1592]
### What
Properties's example isn't being rendered in the docs
![image](https://user-images.githubusercontent.com/83093699/115924445-a0c10580-a477-11eb-8595-2485fa2396a4.png).

### How to reproduce
I used the spec from [Swagger Editor](https://editor.swagger.io/) since there's `example: doggie` under `property: name`:
![image](https://user-images.githubusercontent.com/83093699/115924212-53449880-a477-11eb-850f-73d890bfe494.png) and added `default: default_doggie`:
![image](https://user-images.githubusercontent.com/83093699/115924349-825b0a00-a477-11eb-9fce-09d2e0789d12.png)
and then I run `redoc-cli bundle spec.yaml`. And then here's what I could see when I opened html:
![image](https://user-images.githubusercontent.com/83093699/115924445-a0c10580-a477-11eb-8595-2485fa2396a4.png)

Is that expected?

### Related docs
https://swagger.io/docs/specification/adding-examples/

**Comment by salmipa** [comment]
No, it should not be expected. It works if you rename the examples property to example, but then it's not a valid schema anymore. Very, very nasty bug. I'm going to change the schema on the fly to contain example instead of examples, but it's just plain wrong. On the other hand, I want examples to be rendered.

**Comment by jeremyfiel** [comment]
pending #1058
