### ISSUE TITLE
Hide tag from documentation if it doesn't have any element

### ISSUE THREAD

**Issue by xYundy** [Redocly/redoc#1752]
**Describe the problem to be solved**
I have documentation generator which can optionally add some documentation elements (endpoints) which will not always been in documentation. For now I can't and I don't want add/remove tags programmatically from the OpenAPI doc.

For now when I create a tag and it doesn't have any endpoints - it's still being displayed and for documentation readers it can be misleading.

**Describe the solution you'd like**
If Tag have no endpoints I wan't do hide it completely. 

**Describe alternatives you've considered**
I also thinks it worth to add this "as option" using vendor extensions or Redoc config params, because somebody can use empty tags as docs sections without endpoints.

**Comment by adamaltman** [comment]
This is the desired behavior because people use empty tags as docs sections.

You can, however, remove the tag if it is unused using [openapi-cli](https://github.com/Redocly/openapi-cli) with a [custom decorator](https://redoc.ly/docs/cli/resources/custom-rules/) that would run during the [`bundle` command](https://redoc.ly/docs/cli/commands/bundle/).

**Comment by rubda** [comment]
For future readers of this issue I found this very helpful: https://github.com/Redocly/redocly-cli-cookbook/tree/main/custom-plugin-decorators/remove-unused-tags
