### ISSUE TITLE
Support Custom Components & Parsers

### ISSUE THREAD

**Issue by ziadsawalha** [Redocly/redoc#1757]
**Describe the problem to be solved**
I'd like to customize how some content renders with code.

Examples:
- support MdX components in markdown
- hook into spec parsing so I can filter out features that are only available in specific environments

**Describe the solution you'd like**
- I'd like to be able to provide my own components in `allowedMdComponents`.
- It would be great if there were a bunch of them available already in the repo.

**Describe alternatives you've considered**

**Additional context**
I'd of course like to also have documentation on the interface for components, how they can
interact with other components and the spec.

**Comment by adamaltman** [comment]
This: 

> support MdX components in markdown

Adds a lot of complexity to this project. I don't think we'll pursue it. 

We do support MDX in an commercial version of our product: https://redoc.ly/developer-portal/

**Comment by RomanHotsiy** [comment]
@ziadsawalha as @adamaltman mentioned it adds too much complexity. We're even considering removing existing `allowedMdComponents` at some point.

I'll close this issue for now.

**Comment by hheavener-kyd** [comment]
@RomanHotsiy there are several projects that depend on the rendering of schema definitions in markdown files. For instance, one of our applications has a very extensive schema that depends on this markdown component being supported because it's not tied to an endpoint. This is data that is sent out from our system and the only way to document it properly using Redoc is through the supported `<SchemaDefinition>` tag in a markdown file.

So I would kindly ask that the Redoc team not remove the existing `allowedMdComponents` as it would prevent many groups from being able to document schemas that are not directly related to an endpoint. I would be okay with not adding more since that's part of the draw to paid versions of Redocly but it would be nice if you didn't remove something you've already let people leverage so that many projects (including mine) do not break.

I love this product and this feature and I hope it stays. Thank you for your consideration.
