### ISSUE TITLE
Vulnerable dependencies

### ISSUE THREAD

**Issue by andysmithnf** [Redocly/redoc#1813]
The following 2 dependencies used by redoc have security vulnerabilities:

**marked** Regular Expression Denial of Service (ReDoS)
CWE-1333
CVSS 5.9 MEDIUM

**json-pointer** Prototype Pollution
CWE-1321
CVE-2021-23820
CVSS 5.6

**Comment by damianobarbati** [comment]
Any solution to this?

**Comment by rajeshsusai** [comment]
I believe marked has been updated to address that vulnerability, this repo would need a PR to update to the newer version.

The json-pointer package has an open PR to address the Prototype Pollution vulnerability, but it appears to be blocked: https://github.com/manuelstofer/json-pointer/pull/36

**Comment by jonathan-codaio** [comment]
Hi folks! Any update updating this repo and `redoc-cli` to use the newer version of `marked`?

There is a new vulnerability in `marked`: https://github.com/advisories/GHSA-5v2h-r2cx-5xgj

We are unable to work around this one as we have in the past because it appears that `redoc` and `redoc-cli` produce build errors when we force a resolution of `marked` to `4.0.10`.

As these are high severity vulnerabilities, any chance this could be looked into? Thanks!

**Comment by vjwilson** [comment]
Bumping this for `json-pointer`

Someone has forked that repo and then published a "json-pointer-community" package with the vuln fixed in it.

Is it possible for Redoc to switch to using the updated fork?

[Comment announcing the fork in original issue](https://github.com/manuelstofer/json-pointer/pull/36#issuecomment-1029721176)
[New package with fix](https://www.npmjs.com/package/json-pointer-community)

**Comment by JackElderProscia** [comment]
The owner of `json-pointer` has merged a vulnerability fix and published a new version.

Linking @crenshaw-dev's PR: https://github.com/Redocly/redoc/pull/1910

**Comment by crenshaw-dev** [comment]
Looks like rc64 patches the issue?

**Comment by AlexVarchuk** [comment]
seems it is resolved. If someone has questions/enhancements about that issue, please reopen it and let us know. Thanks.

**Comment by AlexVarchuk** [comment]
seems it is resolved. If someone has questions/enhancements about that issue, please reopen it and let us know. Thanks.
