### ISSUE TITLE
description in generated html mismatch with description in swagger.json

### ISSUE THREAD

**Issue by therealqxing** [Redocly/redoc#1851]
**Describe the bug**
swagger.json
```
    "ingressSourceType": {
      "type": "string",
      "enum": [
        "UNKNOWN"
      ],
      "default": "UNKNOWN",
      "description": "source type."
    },
...
    "example_PlatformParameter": {
      "type": "object",
      "properties": {
        "source_type": {
          "$ref": "#/definitions/ingressSourceType",
          "description": "xxx"
        }
      },
      "description": "platform parameter."
    },
```
The generated html only contains description "source type" in $ref, and miss the "xxx" in example_PlatformParameter.

**Expected behavior**
both description xxx and description in $ref exist in the generated html.

**Comment by AlexVarchuk** [comment]
@therealqxing Hi, thank you for the request.
$ref siblings are supported in OpenAPI 3.1.
I think it is expected behavior.
Try to update your definition to 3.1 versions or try to wrap `$ref` into `allOf`. 
Maybe this [link](https://stackoverflow.com/questions/33629750/swagger-schema-properties-ignored-when-using-ref-why) helps you.
