### ISSUE TITLE
Left Panel not showing

### ISSUE THREAD

**Issue by KyriacosP** [Redocly/redoc#2023]
**Describe the bug**
I'm using the react component of redoc following the guide https://redocly.com/docs/redoc/deployment/react/ but the left panel is not showing up as you can see in the following screenshots.

![redocPetStore](https://user-images.githubusercontent.com/44581807/170231902-2bdb09c7-f1ea-4998-a1ca-3211c7b687bd.PNG)
![redocPetStore2](https://user-images.githubusercontent.com/44581807/170231935-e846cab4-ebd9-4f67-bcae-80aa8bb14c7d.PNG)
![redocPetStore3](https://user-images.githubusercontent.com/44581807/170231944-eb36ed06-af1c-44a2-878b-7fbb04a17b8e.PNG)
![redocPetStore4](https://user-images.githubusercontent.com/44581807/170231958-66cd3d59-6b48-49f5-ac02-5dbfeea6f7cb.PNG)

**Expected behavior**
The expected behavior is to show the left panel by default similar to the online demo

![expected](https://user-images.githubusercontent.com/44581807/170232324-064bd6e4-eb59-4f82-afd0-89eb3e6558fa.PNG)

**Comment by AlexVarchuk** [comment]
@KyriacosP Hi. Thank you a lot for the issue.
Seems it is related to `React 18`. For now, try to downgrade your react version to `17`. 
We are starting to work on it.

**Comment by KyriacosP** [comment]
@AlexVarchuk Thank you it works with react 17.0.2

**Comment by Oprysk** [comment]
@KyriacosP Thanks for reaching out us 🙌 

The problem is in the react 18+ `<React.StrictMode>` tool. It helps determine the rendering problems, side effects etc.
You should not wrap our app by this component in order to avoid package work inconsistency, also this tool enables double rendering (dev and prod) [React Documentation](https://reactjs.org/docs/strict-mode.html)

If you have StrictMode enabled in your app but don't remember enabling it, it might be because you used create-react-app or similar to create your app initially, which automatically enables StrictMode by default.

For example, you might find that your {app} is wrapped by <React.StrictMode> in your index.js:

  ```js
ReactDOM.render(
     <React.StrictMode>
       {app}
     </React.StrictMode>,
    document.getElementById('root')
  );
```


Although we will migrate to the React 18 and going to fix Strict mode related issues in the nearest future. Thank you!
P.S. Feel free to reopen this issue if you have unresolved question 😃
