### ISSUE TITLE
Remove path aliases from Documentation

### ISSUE THREAD

**Issue by jfoclpf** [Redocly/redoc#2238]
**Describe the problem to be solved**

When you have path aliases in `openapi.yaml` with `$ref`, for example

```yaml
paths:
  /municipios/{municipio}:
    get:
      operationId: getMunicipality
      summary: Detalhes sobre Município  
      parameters:
        - in: path
          name: municipio
          required: true
          schema:
            type: string
            example: évora
          allowReserved: true
          description: Município
        - $ref: '#/components/parameters/json'
      responses:
        '200':
          description: Detalhes do Município
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/municipio'

  /municipio/{municipio}:
    $ref: '#/paths/~1municipios~1%7Bmunicipio%7D'
```

`/municipio/{municipio}` is _de facto_ merely a path alias of `/municipios/{municipio}`

In the [documentation](https://docs.geoapi.pt/#operation/getMunicipality) both paths rules and response samples are shown in duplicate.

**Describe the solution you'd like**

I would like to remove path aliases from documentation, that is, basically remove these duplicates, since I just use them due to backward compatibility.

**Describe alternatives you've considered**

I realized this might work in client-side, but I still need to understand how

```js
document.querySelectorAll('div[data-section-id]').forEach(el=> {
    const attr = el.getAttribute('data-section-id'))
    // ...
})
```

**Comment by jfoclpf** [comment]
I realized this might work

```js
document.querySelectorAll('div[data-section-id]').forEach(el=> {
    const attr = el.getAttribute('data-section-id'))
})
```

**Comment by lornajane** [comment]
I don't think we can remove paths from documentation, but we do have tooling that you can use to drop your "extra" paths from the OpenAPI description before rendering documentation. One option is to tag the extra paths as "internal", and then use a decorator to hide those internal APIs from the OpenAPI output. We have a guide on doing this here: https://redocly.com/docs/cli/guides/hide-apis/

I'll close this issue since we're not planning to make changes to Redoc
