### ISSUE TITLE
Example of the openapi specification is 'null' when the component is nested more than four levels deep in a hierarchy

### ISSUE THREAD

**Issue by topus** [Redocly/redoc#2291]
**Describe the bug**
Reproduces with
"@redocly/cli": "1.0.0-beta.124"

When a component is nested too deep in a tree of components, then the corresponding ‘example’ specification of openapi, is not rendered anymore.

**Expected behavior**
In the given example, the same component which describes geo coordinates in latitude and longitude is entered on different hierarchical levels (A->B->C->D->E). The ‘examples’ within the openapi specification on level C and D, are perfectly rendered. However one level deeper, then the specified example isn’t rendered anymore and ‘null’ is shown except of the specified coordinate examples.

From level D , the component is entered in two different ways. Both approaches show that the rendering of the example is not working any more, as only null is shown, instead of the corresponding ‘double’ example

**Minimal reproducible OpenAPI snippet(if possible)**
In attachment a text file, which is an openapi specification in yaml to reproduce the bug.
[openapi-0.1.0.txt](https://github.com/Redocly/redoc/files/11088903/openapi-0.1.0.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/4933921/228226317-53a5df28-e2f9-459d-bbe4-dbdf216da2c3.png)

**Comment by Orest-Yastremskyy** [comment]
Hi @topus 

It is actually not a bug, but expected behaviour. We do have the option to change this behaviour - it is called generatedPayloadSamplesMaxDepth. The default value is 8 but you can change it to 15 for example in your redocly.yaml file:

generatedPayloadSamplesMaxDepth: 15

More configuration options for API docs:

https://redocly.com/docs/api-reference-docs/configuration/functionality/ 

Here is how it looks after I have changed it to 15:

![image](https://user-images.githubusercontent.com/96121440/228488930-c12c218c-47b8-4103-afa7-930c85a237e8.png)


I hope this helps.
