### ISSUE TITLE
Remove the required tag from fields?

### ISSUE THREAD

**Issue by williamle92** [Redocly/redoc#2342]
Hello,
This is related to https://github.com/Redocly/redoc/issues/230

I am using `FastAPI` and `Pydantic` to automatically generate my documentation. Is there any way to remove the `required` tag in fields where we expect a value but still have it validated with Pydantic?

For example, the `UserOut` Model below here will raise an error if `name`, `first_name`, `last_name` or `email` is not a string.
```
class UserOut(BaseModel):
    name: str
    first_name: str
    last_name: str    
    phone_number: Optional[str]
    email: str
```
And in the docs, these fields do not have a `required` tag.

**Comment by romanpryshliak** [comment]
Hi @williamle92,

Could you please share with us more details regarding your use case scenario so we can better understand it in the context of Redoc and assist you accordingly?

**Comment by williamle92** [comment]
Hello @romanpryshliak ,
Thank you for your reply. I am currently using `FastAPI` with `Pydantic` to generate the auto-documentation with `Redoc`. I have included an example picture below:
![image](https://github.com/Redocly/redoc/assets/81194035/d6596477-0d1f-4536-9a03-7739279ce27a)
 While it makes sense to users for the request body schema to have a `Required` tag. We think it may be confusing when the `Required` tag is also in the response as well. I was wondering if there is any way to remove this `Required` tag on all responses. Thank you for your time!

**Comment by AlexVarchuk** [comment]
Hi @williamle92, thank you for your explanation. Redoc does not have a straightforward way to do that. But you can remove all `required` keys from your response schemas using [@redocly/cli](https://www.npmjs.com/package/@redocly/cli) [decorators](https://redocly.com/docs/cli/decorators/). I think it is the best way to do that.

**Comment by williamle92** [comment]
Hello @AlexVarchuk, thanks for your response. 
I tried looking into redocly cli that you referenced, and it seems like it is a javascript-based library. While I think I am mainly interacting with redocly through FastAPI in Python. Is there a Python sdk for redoc cli that I can use to implement this? if not then is it possible to add decorators to redoc through fastapi?

**Comment by lornajane** [comment]
I think there are two questions here:
 * How to tell FastAPI to validate optional fields if it receives data for them - this should be in the documentation for the tool
 * How to use Redocly CLI to change the OpenAPI description. As Alex says, Redocly has functionality for this, but [from this documentation](https://fastapi.tiangolo.com/advanced/extending-openapi/) it looks like you don't actually get access to the OpenAPI file so that you could modify it using other tools. However that same page does show some ways to interact with the resulting data structure from FastAPI, so I suggest you use that to remove the required properties.

The alternative for FastAPI users is to save the OpenAPI file that FastAPI generates, and use it as input to their own API pipelines, including linting, altering if necessary, and finally publishing docs. Hope some of this helps!

**Comment by AlexVarchuk** [comment]
Hi @williamle92, you can use @redocly/cli as part of your pipeline anywhere you need.

**Comment by williamle92** [comment]
Thank you @lornajane and @AlexVarchuk for your responses to this matter. I was able to get it to work by adjusting the open API schema object on FastAPI and setting the `required` field on the response schemas that I wanted to remove the required tag to an empty list based on @lornajane suggestion. Thanks!
