### ISSUE TITLE
multiple api specifications for the docker image redoc

### ISSUE THREAD

**Issue by lamoboos223** [Redocly/redoc#2415]
**Describe the problem to be solved**
the image only supports adding one swagger.

**Describe the solution you'd like**
i want the redoc to read the swagger files from certain directory instead of giving it one file

**Comment by romanpryshliak** [comment]
Hi @lamoboos223, 

Could you please describe your use case in more detail? Would you like Redoc to read the swagger files from a certain directory to be able to display multiple versions of your API documentation on a single site?

**Comment by lamoboos223** [comment]
Hi @romanpryshliak 

For example if i had 3 swaggers like company.yaml, twitter.yaml, myservice.yaml

I want each swagger to be displayed as a single site or perhaps if there is a dropdown list where I can select which swagger i want to view.

**Comment by romanpryshliak** [comment]
@lamoboos223,

Thank you for the clarification. I have added your suggestion to our list of ideas so that our Product Team can evaluate how it fits our roadmap.

I would also like to mention that we already offer a feature to select an API version from the dropdown in our paid product - Redocly. For more details, please refer to the article below:
https://redocly.com/docs/workflows/docs/multiple-versions/

**Comment by lamoboos223** [comment]
It looks amazing! Thank you for sharing that. I’m actually want to deploy redoc on my homelab so i can test my localhost services freely and free. That’s why I was hoping to add the feature to the open source project 😅.

thank you 🙏🏻🌹
@romanpryshliak

**Comment by lornajane** [comment]
Thanks for the suggestion @lamoboos223 . The docker functionality is now part of the Redocly CLI repo, and there's an issue already open there that I think would meet your needs. Please follow along in https://github.com/Redocly/redocly-cli/issues/1294 for updates, and I'll close this issue (but let us know if you need anything else!)
