### ISSUE TITLE
Static CSS Names? 

### ISSUE THREAD

**Issue by cb911nr** [Redocly/redoc#2454]
This is probably the wrong place, but can't quite find an answer after extensive google searching and documentation reading, actually quite surprised I am having trouble finding an answer haha..

So I am trying to get help from someone.

We're using the standalone redoc, it loads the swagger json file, everything is good.

However we want to really customize the CSS, but it generates classes like "sc-eeDRCY sc-eBMEME gvJSKt hzUya" making it hard to change. Am I missing something here? I could target those classes, but I fear they will randomly change with different releases.

**Comment by romanpryshliak** [comment]
Hi @cb911nr,

At present, Redoc doesn't have static CSS classes since they will limit our ability to maintain it without introducing breaking changes (see the corresponding discussion [here](https://github.com/Redocly/redoc/pull/2159)).

Please note that you can utilize [out-of-the-box theming options](https://redocly.redoc.ly/docs/redoc/config/#theme-settings) to style Redoc.

If the aforementioned theming options don't suit your needs, I may suggest finding a custom selector that would not change over time and using it to target areas of the docs you would like to style.

As we don't have immediate plans to implement this enhancement, I'll close this issue. Should you have any further queries on this topic, feel free to reopen it.

**Comment by dylanh724** [comment]
Curious, why do I need to login to see that doc?
