### ISSUE TITLE
This search cannot be used properly

### ISSUE THREAD

**Issue by HHC26** [Redocly/redoc#2540]
This search cannot be used properly, need to improve this bug
![image](https://github.com/Redocly/redoc/assets/44391821/a1505785-5cfd-43dc-8699-eceae8ba3927)

**Comment by AlexVarchuk** [comment]
Hi @HHC26, thank you for reporting. PRs are welcome or we can look into it later.

If you want to disable search and implement custom you can do it using `disableSearch` option.

**Comment by miqh** [comment]
@AlexVarchuk,

The search term "get" would've never yielded results because Lunr is being configured with `stopWordFilter`. This change appears to have been in place for a long time now.

https://github.com/Redocly/redoc/blob/d193dd2627b88309eca3cec4973ba5bea2906740/src/services/SearchWorker.worker.ts#L31

If you take a look at the implementation of this filter, it includes the word "get".

https://github.com/olivernn/lunr.js/blob/aa5a878f62a6bba1e8e5b95714899e17e8150b38/lib/stop_word_filter.js#L78

If `stopWordFilter` is redacted, the search results for the demo should include GET-based endpoints.

![Image](https://github.com/user-attachments/assets/1a9975c2-0119-481f-919d-7e7879bc8e53)

I'd be happy to submit a pull request to remove it altogether, or to put the removal behind some kind of global setting.

**Comment by ivankropyvnytskyi** [comment]
I tested and cannot reproduce the issue.
