### ISSUE TITLE
Possible XSS issue on https://redocly.github.io/redoc/

### ISSUE THREAD

**Issue by romanpryshliak** [Redocly/redoc#2548]
**Describe the bug**

https://redocly.github.io/redoc/ renders the `<input>` tags.

**Minimal reproducible OpenAPI snippet(if possible)**

```yaml
openapi: 3.0.3
info:
  title: Sample API
  description: This is a sample API to demonstrate OpenAPI specifications.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /greet:
    get:
      summary: Greet the user
      description: Returns a greeting message <input>.
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, User!"
```

**Screenshots**

![image](https://github.com/Redocly/redoc/assets/92374352/bc05b634-ad30-4d66-af55-84c91ef81a56)

**Comment by RomanHotsiy** [comment]
@AlexVarchuk I think it's off by default. We need to enable it for our demo.

**Comment by AlexVarchuk** [comment]
We have `untrustedSpec: true` inside our [demo](https://github.com/Redocly/redoc/blob/3658b6def49413a8626d9c591c2ba4e01de5e83e/demo/index.tsx#L125C11-L125C66).

I also made separate tests with this string, and they work the same way. Regarding documentation `dompurify`, cleans attributes, and events inside HTML. It seems it considers this case not critical because it works in other cases.
