### ISSUE TITLE
Description of properties with a schema reference does not get rendered

### ISSUE THREAD

**Issue by ash23** [Redocly/redoc#453]
"swagger":"2.0",
...
...
"definitions":{ 
... 
...
"FooDto": {
"type":"object",
 "properties":{ 
 "localDateTimePeriod":{  
               "$ref":"#/definitions/LocalDateTimePeriodDto",
               "description":"This description is NOT rendered by ReDoc"
            },
 "organisationNodeId":{  
               "description":"This description IS rendered by ReDoc",
               "type":"string"
            }
...
...
"LocalDateTimePeriodDto":{
         "required":[
            "startLocalDateTime",
            "endLocalDateTime"
         ],
         "type":"object",
         "properties":{
            "startLocalDateTime":{
               "type":"string"
            },
            "endLocalDateTime":{
               "type":"string"
            }
         }
      }

**Comment by cdtinney** [comment]
I believe this is correct as there should not be any sibling properties of `$ref` -- they are ignored.

**Comment by RomanGotsiy** [comment]
@cdtinney is correct.

All the siblings of `$ref` are ignored according to the spec.
To workaround this you can use the following trick:

```js
"localDateTimePeriod":{
  "description":"This description is NOT rendered by ReDoc"
  "allOf": [{
    "$ref":"#/definitions/LocalDateTimePeriodDto",
  }]
},

**Comment by darklynx** [comment]
Actually all tools from Swagger (Swagger UI, Swagger Codegen, etc.) interpret the rule different than you do and they respect the description next to the `$ref` property it overrides the description of the referred object.

In this case, when 2 `description` are supplied, the `description` on the property level is attached to the **property**, whereas `description` on the level of referred object is attached to the **class** that represents the reference. In most of the OOP languages that is a valid concept.

I also supplied a PR #703 for ReDoc 1.x, but now I see why my PR might not pass through.

That's pity, because [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) tool **fails to generate** classes properly when you use `allOf` on the property level. That is a harsh trade-off: you can either please ReDoc to render description with `allOf` approach, of focus on developers needs to generate valid models from your schema and ignore the fact that in some cases ReDoc won't show a proper description.

**Comment by RomanGotsiy** [comment]
> interpret the rule different than you do and they respect the description next to the $ref property
That's the issue with OpenAPI. Too many edge cases and each tool interprets them differently.

Adhering to this rule complicates circular dependency detection which is already tooo messy and complex.

But I see your points. I will try to fix it.

**Comment by JSSAggie** [comment]
This has been open for a while and is a real pain.  Is there a reason why this is not getting addressed?  Is this something you want to support just need time to do it?

**Comment by Blacklands** [comment]
Should tooling support things that go explicitly against the OpenAPI specification?
Doesn't this just make the confusion worse? I can see the problem for things where the spec is ambiguous/unclear, but that Reference Objects cannot have siblings is clearly started (e.g. [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#reference-object)), and I think most linting tools out there will warn you about it.

Also, for the record, this [will be possible](https://github.com/OAI/OpenAPI-Specification/issues/556#issuecomment-590412421)\* in OpenAPI 3.1, which just got its first Release Candidate.
(\* Only for Schema Objects, though, as far as I understand it.)

So maybe this would be a good time for adding support for this now?

**Comment by RomanHotsiy** [comment]
Yes, we are looking into this. We'll see if we can get it before 2.0

**Comment by caligo-erik** [comment]
Just bumped (again) into this specific issue:
I think the problem is that there are actually **two** levels for these fields, e.g. description and deprecated.

### Example: 
I have a schema Address that I re-use in various places. Now I'd like to rename one of the fields referencing it, in this case shipmentAddress. So the old property should be deprecated. What I'd like to is this:
```
shipmentAddress:
  description: deprecated. destination address of the shipment
  deprecated: true
  $ref: "#/components/schemas/Address"
destinationAddress:
  description: destination address of the shipment
  $ref: "#/components/schemas/Address"
billingAddress:
  description: address the bill will be sent to
  $ref: "#/components/schemas/Address"
...
Address:
  description: structured address information.
  properties: 
...
```
This is not "allowed by specs definition" and coherently ignored by most documentation and code generation tools.

### Current workaround:
Without the possibility to separate between schema description and property description, I need to duplicate the schema of the property if I want to add some verbose information, or if I want to deprecate a schema which is still used elsewhere, again I need to duplicate it, and add _deprecated: true_ within that schema. 

### Maybe it is wrong?
To explain this point per absurdum: imagine having the field required at schema level, rather than at property level. If you then had one address that is required and an optional second address which isn't, you would have to duplicate that schema, one with required: true, and one with required: false. Why would I want to have the same description for the billing address and the shipping address?

### Proposal
The only long time solution I see is to allow for and distinguish between schema.description and property.description. The property.description describes the property (as it already does with scalar data types, e.g. string) and the schema.description adds generic information about that schema. Similar consideration goes for deprecated, so you can distinguish between a property that no longer is in use (string, bool, or referenced object, no difference) and a deprecated schema. It would then also make sense that any validation and code generation tool should throw an error, if there is a "non-deprecated" property referencing a deprecated schema.

**Comment by danydev** [comment]
This issue duplicates https://github.com/Redocly/redoc/pull/1381
Anyway this is allowed in Open API 3.1

**Comment by caligo-erik** [comment]
> This issue duplicates #1381
> Anyway this is allowed in Open API 3.1, so I guess it's just matter of time to have it. Once redocly supports 3.1 we'll have it.

Great news!

**Comment by AlexVarchuk** [comment]
We now have basic support for OpenAPI 3.1 with this feature supported.
