### ISSUE TITLE
Feature Request: Navigation Sorting

### ISSUE THREAD

**Issue by gmr** [Redocly/redoc#98]
I just saw this tonight and have already started to roll it out for my APIs.

One nit is the ordering of the sidebar navigation seems to be fairly random.

It'd be awesome if I could sort endpoints in the navigation with an `x-` variable or by setting a configuration value that told it to sort alpha by `operationId` or `summary`.

**Comment by RomanGotsiy** [comment]
> already started to roll out
👍  🎉 

Currently, methods are grouped by tags (similar to the SwaggerUI) and tags (top level menu items) are sorted according to the order of [`tags` field](https://github.com/OAI/OpenAPI-Specification/blob/master//versions/2.0.md#swagger-object).

Inside tags methods are ordered in the same order as the appear in json/yaml spec (yes I know json doesn't have an order but in all modern javascript engines it appears to have 😄 )

If you have many endpoints - tags are a good way to organize things.
If this doesn't work for you, we can discuss some option or `x-` vendor extension.

**Comment by gmr** [comment]
I have the tags for organizing, I was more interested in the actual endpoint/method sorting.  I've also noticed request and response parameter sorting doesn't match the spec as well.

It seems the sorting is deterministic, but not based upon the document as far as I can tell.

I was thinking an ``x-sort-order`` or something might be a good way to go, but perhaps I'm missing something.

Thanks BTW, this is exactly what I was looking for when I started [this](https://github.com/gmr/oaui/tree/initial-version).

**Comment by jonyw4** [comment]
I need this feature too. How I can support? +1

**Comment by slavcodev** [comment]
I'm interesting in the order of side menu too. And this is my proposal.

The headers from the `info` description are rendering as menu items now. Also ReDoc already supports kind of "widgets system" using HTML comment for the injection of the security definitions. I propose to use these features further. There is example how to inject operations in the `info` description:

~~~yaml
info:
  description: |
    # Introduction
    ...
    # Group e.g. Pet

    ## Add a new pet to the store
    <!-- see: #/paths/~1pet/post -->

    ## Update an existing pet
    <!-- see: #/paths/~1pet/put -->
tags:
  - name: Pet
    description: Everything about your Pets
  - name: Store
    description: Access to Petstore orders
paths:
  /pet:
    post:
      tags:
        - pet
      summary: Add a new pet to the store
    put:
      tags:
        - pet
      summary: Update an existing pet
~~~

The conventional rules:

1) The operation summary should be same as the header title.
2) The operations missing from `info` will be rendered by usual in menu item by tag.
3) If header title coincides with tag name, tag description will be injected in `info`

And optional, ReDoc can support different header levels for operations, in order to extended group ing. E.q.

~~~yaml
info:
  description: |
    # Introduction
    ...
    # Group

    ## Sub-group
    <!-- see: #/paths/~1pet/post -->
    ### Add a new pet to the store

    ## Sub-group
    ### Update an existing pet
    <!-- see: #/paths/~1pet/put -->
~~~

**Comment by fenollp** [comment]
We'd also would love to have this as an option. Maybe `--options.sortNavigationTags=true`?

**Comment by AndriiMz** [comment]
@fenollp @RomanHotsiy 

added made some changes locally and added "sortNavigationTags" option:
![image](https://user-images.githubusercontent.com/33951805/88187024-4e2b9200-cc36-11ea-977d-f6d7bd20db7c.png)
![image](https://user-images.githubusercontent.com/33951805/88187082-5daadb00-cc36-11ea-9b2e-f11dbd560a3b.png)
![image](https://user-images.githubusercontent.com/33951805/88187102-656a7f80-cc36-11ea-9dd3-3453aa5ca9f5.png)
![image](https://user-images.githubusercontent.com/33951805/88187148-76b38c00-cc36-11ea-8965-a095d62aa4b4.png)

tests passed, can we discuss and make a or with such feature? it's we important for our team.

**Comment by adamaltman** [comment]
FYI: they are sorted by the order they are defined in `paths` now in the root definition file.

**Comment by damianobarbati** [comment]
@AndriiMz @adamaltman I didn't quite get it: what's the intended way to impose a specific order in methods under a tag?
MyTag >
    /my/first
    /my/second
    /third-this-one

**Comment by adamaltman** [comment]
> they are sorted by the order they are defined in paths now in the root definition file.

```
paths:
  My-first-path: ...
  My-second-path: ...
  My-third-path: ...
```

**Comment by RomanHotsiy** [comment]
We have implemented two options a while ago: `sortOperationsAlphabetically` and `sortTagsAlphabetically`.

**Comment by GCSBOSS** [comment]
I have come across a restriction in some tooling, where tags must be always defined alphabetically in the spec file. Is this something to be considered?

I'm as of now unable to order my tags by switching places in the file. Is this worth it an option or extension?

**Comment by adamaltman** [comment]
>  We have implemented two options a while ago: sortOperationsAlphabetically and sortTagsAlphabetically.

**Comment by avin-kavish** [comment]
> I mean to order my tags in the order the API user should start interacting with each entity in the system. Essentially a custom order.

+1

> paths:
>   My-first-path: ...
>   My-second-path: ...
>   My-third-path: ...

  
  This doesn't work because paths are like,
  
  - `/v1/todos/{id}`
     - GET
     - POST
     - PUT
     - DELETE
- `/v1/todos`
    - GET

And I want the order to be like,

- `/v1/todos/{id}`
   - POST
   - GET
- `/v1/todos`
  - GET
- `/v1/todos/{id}` 
  - PUT
  - DELETE

But since `paths` is an object it's not valid syntax to duplicate keys.

**Comment by JoseHCalderon** [comment]
Alguna idea de como hacer ese sort por paths
